#spring:
#  rabbitmq:
#    addresses: 192.168.159.130
#    username: guest
#    password: guest
#    port: 5672

spring:
  datasource:
    url: jdbc:mysql://gflish.xyz:7083/tangram?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: dev
    password: 123456
    driver-class-name: com.alibaba.druid.proxy.DruidDriver