// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package com.github.cooker.core;

public final class RickType {
  private RickType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.github.cooker.core.messageType}
   */
  public enum messageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FILE = 0;</code>
     */
    FILE(0),
    /**
     * <code>METHOD = 1;</code>
     */
    METHOD(1),
    /**
     * <code>LOG = 2;</code>
     */
    LOG(2),
    /**
     * <code>UNKNOWN = 3;</code>
     */
    UNKNOWN(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FILE = 0;</code>
     */
    public static final int FILE_VALUE = 0;
    /**
     * <code>METHOD = 1;</code>
     */
    public static final int METHOD_VALUE = 1;
    /**
     * <code>LOG = 2;</code>
     */
    public static final int LOG_VALUE = 2;
    /**
     * <code>UNKNOWN = 3;</code>
     */
    public static final int UNKNOWN_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static messageType valueOf(int value) {
      return forNumber(value);
    }

    public static messageType forNumber(int value) {
      switch (value) {
        case 0: return FILE;
        case 1: return METHOD;
        case 2: return LOG;
        case 3: return UNKNOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<messageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        messageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<messageType>() {
            public messageType findValueByNumber(int number) {
              return messageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.cooker.core.RickType.getDescriptor().getEnumTypes().get(0);
    }

    private static final messageType[] VALUES = values();

    public static messageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private messageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.cooker.core.messageType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntype.proto\022\026com.github.cooker.core\032\031go" +
      "ogle/protobuf/any.proto\032\037google/protobuf" +
      "/timestamp.proto*9\n\013messageType\022\010\n\004FILE\020" +
      "\000\022\n\n\006METHOD\020\001\022\007\n\003LOG\020\002\022\013\n\007UNKNOWN\020\003B\nB\010R" +
      "ickTypeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
